#!/usr/bin/env ruby

#-------------------------------------------------------------------------------
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not exceed
# four million.
#-------------------------------------------------------------------------------

limit = 4000000
i = 0
a = 1
b = 2
sum = 2

until sum > limit
  a, b = b, a + b
  if b % 2 == 0
    sum += b
  end
end

puts sum


