;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
;; By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million,
;; find the sum of the even-valued terms.

(defn fibs [fs]
  (def next_fib (+ (first fs) (first (rest fs))))
  (if (> next_fib 4000000)
    fs
    (fibs (cons next_fib fs))
  )
)

(println (reduce + (filter even? (fibs `(2 1)))))
